// <auto-generated />
namespace WellaMates.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class ManagerIdentification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ManagerIdentification));
        
        string IMigrationMetadata.Id
        {
            get { return "201403072227169_ManagerIdentification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
